name: viz-ci-build
on: [workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          # Any higher and we need to update vizes to use webpack 5
          node-version: '16'

      - name: Install dependencies and build/bundle
        run: |
          yarn install --immutable --immutable-cache --check-cache
          yarn build
