name: test primary version
on:
  workflow_dispatch:

jobs:
  setup:
    uses: looker-open-source/reusable-actions/.github/workflows/primary-version.yml

  test:
    name: test
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, ${{ fromJson(needs.setup.outputs.matrix_json)[0] }}

  test-matrix:
    name: test - ${{ matrix.looker }}
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        looker: ${{ fromJson(needs.setup.outputs.matrix_json) }}

    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, ${{ matrix.looker }}
